<?php

use Laminas\Mvc\Application;
?>
<!-- Header -->
<header class="header" id="top">
    <div class="text-vertical-center">
        <h1 class="index-title">A 404 error occurred</h1>
        <h3 class="index-sub-title">a (un)common name</h3>
    </div>
</header>


<section id="error" class="error">
        <div class="col-lg-12">
            <h2 class="text-center"><?= $this->message ?></h2>
        </div>
</section>
