<section id="stravaOverview" class="pt-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col">
                <h2>Run stats</h2>
                <hr class="small">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12  col-md-2 col-lg-2 mb-5">
                <div class="card bg-success">
                    <div class="card-header text-center">
                        <i class="fa fa-running"></i>
                        <h5 class="card-title text-center mt-2">Totaal activiteiten</h5>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center"><?= $totalRunActivities ?></h5>
                    </div>
                </div>
            </div>
            <div class="col-sm-12  col-md-2 col-lg-2 mb-5">
                <div class="card bg-warning">
                    <div class="card-header text-center">
                        <i class="fas fa-tachometer-alt"></i>
                        <h5 class="card-title text-center mt-2">Gemiddelde tempo</h5>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            <?= $this->stravaViewHelper()->getAverageSpeed($averageSpeed) ?>
                        </h5>
                    </div>
                </div>
            </div>
            <div class="col-sm-12  col-md-2 col-lg-2 mb-5">
                <div class="card bg-secondary">
                    <div class="card-header text-center">
                        <i class="fas fa-road"></i>
                        <h5 class="card-title text-center mt-2">Totaal km's</h5>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            <?= $this->stravaViewHelper()->getDistance($totalRunDistance) ?> km
                        </h5>
                    </div>
                </div>
            </div>
            <div class="col-sm-12  col-md-2 col-lg-2 mb-5">
                <div class="card bg-dark">
                    <div class="card-header text-center">
                        <i class="fas fa-stopwatch"></i>
                        <h5 class="card-title text-center mt-2">Totaal tijd</h5>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            <?= $this->stravaViewHelper()->getTotalMovingTime($totalRunTime); ?>
                        </h5>
                    </div>
                </div>
            </div>
            <div class="col-sm-12  col-md-2 col-lg-2 mb-5">
                <div class="card bg-info">
                    <div class="card-header text-center">
                        <i class="fas fa-mountain"></i>
                        <h5 class="card-title text-center mt-2">Gemiddelde hoogteverschil</h5>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            <?= $this->stravaViewHelper()->getTotalElevationGain($averageElevation); ?>
                        </h5>
                    </div>
                </div>
            </div>
            <div class="col-sm-12  col-md-2 col-lg-2 mb-5">
                <div class="card bg-danger">
                    <div class="card-header text-center">
                        <i class="fas fa-heartbeat"></i>
                        <h5 class="card-title text-center mt-2">Gemiddelde hartslag</h5>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            <?= $this->stravaViewHelper()->getTotalElevationGain($averageHeartbeat); ?>
                        </h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="row text-center pb-3">
            <div class="col">
                <a href="<?php echo $this->url('runningStats'); ?>" class="btn btn-dark btn-lg"><i class="fas fa-chart-bar fa-3x"></i></a>
            </div>
        </div>
    </div>
</section>