<section id="services" class="services bg-primary text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-10 mx-auto">
                <h2>Tweets</h2>
                <hr class="small">
                <div class="row">
                    <?php foreach ($tweets AS $index => $tweet) { ?>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <h4 class="twitter-title">
                                    <strong><?php echo $tweet["tweet_date"]; ?></strong>
                                </h4>
                                <p><?php echo $tweet["tweet_text"]; ?></p>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.col-lg-10 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>