<?php
$this->layout('layout/beheer');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->headTitle('Roles');

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Roles' => $this->url('roles'),
]);
?>
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">ROLES BEHEER</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div class="row mb-2">
    <div class="col">
        <a class="btn btn-secondary" href="
           <?= $this->url('roles', ['action' => 'add']); ?>">
            <i class="fas fa-plus-square"></i> New Role
        </a>
    </div>
</div>
<div class="row">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Date Created</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($roles as $role): ?>
                <tr>
                    <td><?= $this->escapeHtml($role->getId()); ?></td>
                    <td>
                        <a href="<?= $this->url('roles', ['action' => 'view', 'id' => $role->getId()]); ?>">
                            <?= $this->escapeHtml($role->getName()); ?>
                        </a>
                    </td>
                    <td><?= $this->escapeHtml($role->getDescription()); ?></a>
                    </td>
                    <td>
                        <nobr><?= (is_object($role->getDateCreated()) ? $this->escapeHtml($role->getDateCreated()->format('Y-m-d')) : ''); ?></nobr>
                    </td>
                    <td class="text-center">
                        <a class="btn btn-secondary btn-sm"
                           href="<?= $this->url('roles', ['action' => 'edit', 'id' => $role->getId()]);
                           ?>">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-danger btn-sm"
                           href="<?= $this->url('roles', ['action' => 'delete', 'id' => $role->getId()]);
                           ?>">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>



