<?php
$this->layout('layout/beheer');
$this->headTitle('Add Permission');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->mainMenu()->setActiveItemId('addpermission');

$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Permissions' => $this->url('beheer/permissions'),
    'Add Permission' => $this->url('beheer/permissions', ['action' => 'add'])
]);

$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter name'
]);

$form->get('description')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter description'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">ADD PERMISSIONS</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div class="row">
    <div class="col">
        <p>
            Please fill out the following form and click the <i>Create</i> button.
        </p>

        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>


