<?php
$this->headTitle('Edit Permission');

$this->mainMenu()->setActiveItemId('overviewpermissions');

$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Permissions' => $this->url('beheer/permissions'),
    'Edit Permission' => $this->url('beheer/permissions', ['action' => 'edit', 'id' => $permission->getId()])
]);

$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter name'
]);

$form->get('description')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter description'
]);

$form->get('submit')
        ->setAttributes(['class' => 'btn btn-primary'])
        ->setValue('Save');

$form->prepare();
?>
<hgroup class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">Edit Permission</h1>
</hgroup>
<div class="col-sm-12 col-md-12 col-lg-12">
    <?= $this->form()->openTag($form); ?>

    <div class="form-group">
        <?= $this->formLabel($form->get('name')); ?>
        <?= $this->formElement($form->get('name')); ?>
        <?= $this->formElementErrors($form->get('name')); ?>                  
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('description')); ?>
        <?= $this->formElement($form->get('description')); ?>
        <?= $this->formElementErrors($form->get('description')); ?>                  
    </div>

    <?= $this->formElement($form->get('csrf')); ?>

    <?= $this->formElement($form->get('submit')); ?>

    <?= $this->form()->closeTag(); ?>
</div>   
