<?php
$this->headTitle('Permissions');

$this->mainMenu()->setActiveItemId('overviewpermissions');

$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Permissions' => $this->url('beheer/permissions'),
]);
?>


<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<hgroup class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">Manage Permissions</h1>
</hgroup>
<div class="col-sm-12 col-md-12 col-lg-12">
    <p>
        <a class="btn btn-default" href="
           <?= $this->url('beheer/permissions', ['action' => 'add']); ?>">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Permission
        </a>
    </p>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Date Created</th>
            <th>Actions</th>        
        </tr>
        <?php foreach ($permissions as $permission): ?>

            <tr>
                <td><?= $this->escapeHtml($permission->getId()); ?></td>
                <td>
                    <a href="<?= $this->url('beheer/permissions', ['action' => 'view', 'id' => $permission->getId()]); ?>">
                        <?= $this->escapeHtml($permission->getName()); ?>
                    </a> 
                </td>
                <td><?= $this->escapeHtml($permission->getDescription()); ?></a> 
                </td>
                <td><nobr><?= (is_object($permission->getDateCreated()) ? $permission->getDateCreated()->format('d-m-Y') : ''); ?></nobr></td>        
            <td>
            <nobr>
                <a class="btn btn-info" href="<?= $this->url('beheer/permissions', ['action' => 'edit', 'id' => $permission->getId()]);
                        ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                </a>
                <a class="btn btn-danger" href="<?= $this->url('beheer/permissions', ['action' => 'delete', 'id' => $permission->getId()]);
                        ?>">
                    <span class="glyphicon glyphicon-remove"></span> Delete
                </a>
            </nobr>
            </td>    
            </tr>
        <?php endforeach; ?>   
    </table>
</div>