<?php
$this->headTitle('View Permission');

$this->mainMenu()->setActiveItemId('overviewpermissions');

$this->pageBreadcrumbs()->setItems([
    'BEheer' => $this->url('beheer'),
    'Manage Permissions' => $this->url('beheer/permissions'),
    'View Permission' => $this->url('beheer/permissions', ['action' => 'view', 'id' => $permission->getId()])
]);
?>


<hgroup class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">View Permission</h1>
</hgroup>

<div class="col-sm-12 col-md-12 col-lg-12">
    <table class="table table-striped table-bordered">
        <tr>
            <th>ID:</th>
            <td><?= $this->escapeHtml($permission->getId()) ?></th>
        </tr>
        <tr>
            <th>Name:</th>
            <td><?= $this->escapeHtml($permission->getName()) ?></th>
        </tr>
        <tr>
            <th>Description:</th>
            <td><?= $this->escapeHtml($permission->getDescription()) ?></th>
        </tr>
        <tr>
            <th>Date Created:</th>
            <td><?= (is_object($permission->getDateCreated()) ? $permission->getDateCreated()->format('d-m-Y') : ''); ?></th>
        </tr>
    </table>
</div>