<?php
$this->headTitle('Sign in');
$this->mainMenu()->setActiveItemId('login');
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Sign in' => $this->url('login'),
]);

$form->get('email')->setAttributes([
            'class' => 'form-control',
            'placeholder' => 'Email address',
            'required' => true,
            'autofocus' => true
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);

$form->get('password')->setAttributes([
            'class' => 'form-control',
            'placeholder' => 'Password',
            'required' => true,
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);
?>
<!-- Page Header -->
<header class="masthead" style="background-image: url('img/bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1 class="index-title">Sign in</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Breadcrumbs -->
<?= $this->pageBreadcrumbs()->render(); ?>
<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-preview">
                <form class="form-signin" method="post">
                    <h2 class="form-signin-heading">Please sign in</h2>
                    <?php if ($isLoginError): ?>
                        <div class="alert alert-warning" role="alert">
                            Incorrect login and/or password. 
                            <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
                        </div>
                    <?php endif; ?>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('email')); ?>
                        <?= $this->formElement($form->get('email')); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('password')); ?>
                        <?= $this->formElement($form->get('password')); ?>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <?= $this->formElement($form->get('remember_me')); ?> Remember me
                            </label>
                        </div>
                    </div>
                    <?= $this->formElement($form->get('redirect_url')); ?>
                    <?= $this->formElement($form->get('csrf')) ?>
                    <button class="btn btn-lg btn-dark btn-block" type="submit">Sign in</button>
                </form>
            </div>
        </div>
    </div>
</div>
