<?php
$this->headTitle("Not Authorized");
?>

<!-- Header -->
<header class="header" id="top">
    <div class="text-vertical-center">
        <h1 class="index-title">Not Authorized</h1>
        <h3 class="index-sub-title">Please login to see this page.</h3>
    </div>
</header>


<section id="error" class="error">
        <div class="col-lg-12">
            <h2 class="text-center">Sorry, you have no permission to see this page.</h2>
        </div>
</section>