<?php
$this->mainMenu()->setActiveItemId('beheer');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">BEHEER</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div class="row">
    <p class="col">
        Welkom in de beheer omgeving.
    </p>
</div>
<div class="row">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Aanhef</th>
                    <th>Naam</th>
                    <th>E-mail</th>
                    <th>Onderwerp</th>
                    <th>Verstuurd op</th>
                    <th class="text-center"><i class="fas fa-cogs"></i></th>
                </tr>
            </thead>
            <tbody>
            <?php if (count($contactForms) > 0) { ?>
                <?php foreach ($contactForms AS $contactForm) { ?>
                    <tr>
                        <td><?php echo $contactForm->getSalutation(); ?></td>
                        <td><?php echo $contactForm->getName(); ?></td>
                        <td><?php echo $contactForm->getEmail(); ?></td>
                        <td><?php echo $contactForm->getSubject(); ?></td>
                        <td><?php echo(is_object($contactForm->getDateCreated()) ? $contactForm->getDateCreated()->format('d-m-Y') : ''); ?></td>
                        <td class="text-center"><i class="fas fa-envelope"></i></td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <td colspan="7" class="text-center">Geen contactformulieren gevonden.</td>
            <?php } ?>
            </tbody>
        </table>
        <?php if (count($contactForms) > 0) { ?>
            <a href="<?php echo $this->url('beheer/contact'); ?>" class="btn btn-dark">Alle berichten</a>
        <?php } ?>
    </div>
</div>