<?php
$this->mainMenu()->setActiveItemId('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
]);
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">BLOG BEHEER</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<p class="col-lg-12 col-md-12 col-sm-12">
    Welkom in de beheer omgeving.
</p>
<div class="col-lg-12 col-md-12 col-sm-12">
    <table class="table table-bordered table-hover">
        <tr>
            <th>Aanhef</th>
            <th>Naam</th>
            <th>E-mail</th>
            <th>Onderwerp</th>
            <th>Verstuurd op</th>
            <th class="text-center"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
        <?php if (count($contactForms) > 0) { ?>
            <?php foreach ($contactForms AS $contactForm) { ?>
                <tr>
                    <td><?php echo $contactForm->getSalutation(); ?></td>
                    <td><?php echo $contactForm->getName(); ?></td>
                    <td><?php echo $contactForm->getEmail(); ?></td>
                    <td><?php echo $contactForm->getSubject(); ?></td>
                    <td><?php echo (is_object($contactForm->getDateCreated()) ? $contactForm->getDateCreated()->format('d-m-Y') : ''); ?></td>
                    <td class="text-center"><span class="glyphicon glyphicon-envelope"></span></td>
                </tr>
            <?php } ?>


        <?php } else { ?>
            <td colspan="7" class="text-center">Geen contactformulieren gevonden.</td>
        <?php } ?>
    </table>
    <?php if (count($contactForms) > 0) { ?>
        <a href="<?php echo $this->url('beheer/contact'); ?>" class="btn btn-action">Alle berichten</a>
    <?php } ?>
</div>