<?php
$this->layout('layout/beheer');
$this->headTitle('Add User');

$this->mainMenu()->setActiveItemId('adduser');

$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Users' => $this->url('beheer/users'),
    'Add User' => $this->url('beheer/users', ['action' => 'add'])
]);

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'name@example.com'
]);

$form->get('full_name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'John Doe'
]);

$form->get('status')->setAttributes([
    'class' => 'form-control'
]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter password',
]);

$form->get('confirm_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Retype password',
]);

$form->get('roles')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<hgroup class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">ADD USERS</h1>
</hgroup>
<div class="col-sm-12 col-md-12 col-lg-12">
    <p>
        Please fill out the following form and click the <i>Create</i> button.
    </p>


    <?= $this->form()->openTag($form); ?>

    <div class="form-group">
        <?= $this->formLabel($form->get('email')); ?>
        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>                  
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('full_name')); ?>
        <?= $this->formElement($form->get('full_name')); ?>
        <?= $this->formElementErrors($form->get('full_name')); ?>                  
    </div>
    
    <div class="form-group">
        <?= $this->formLabel($form->get('password')); ?>
        <?= $this->formElement($form->get('password')); ?>
        <?= $this->formElementErrors($form->get('password')); ?>                  
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('confirm_password')); ?>
        <?= $this->formElement($form->get('confirm_password')); ?>
        <?= $this->formElementErrors($form->get('confirm_password')); ?>                  
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('status')); ?>
        <?= $this->formElement($form->get('status')); ?>
        <?= $this->formElementErrors($form->get('status')); ?>                  
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('roles')); ?>
        <?= $this->formElement($form->get('roles')); ?>
        <?= $this->formElementErrors($form->get('roles')); ?>                  
    </div>

    <?= $this->formElement($form->get('submit')); ?>

    <?= $this->form()->closeTag(); ?>
</div>   
