<?php
$this->layout('layout/beheer');
$this->headTitle('Change Password');

$this->mainMenu()->setActiveItemId('users');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Users' => $this->url('beheer/users'),
    'Change Password' => $this->url('beheer/users', ['action' => 'change-password', 'id' => $user->getId()])
]);

$form->get('old_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter old password'
]);

$form->get('new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter new password'
]);

$form->get('confirm_new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Re-enter new password'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col" id="index">Change Password for <?= $this->escapeHtml($user->getEmail()) ?></h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div class="row">
    <div class="col">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('old_password')); ?>
            <?= $this->formElement($form->get('old_password')); ?>
            <?= $this->formElementErrors($form->get('old_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
