<?php
$this->layout('layout/beheer');
$this->headTitle('Users');
$this->mainMenu()->setActiveItemId('overviewusers');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Users' => $this->url('beheer/users'),
]);
?>

<!-- Page Header -->
<div class="row">
    <h1 class="col">USER BEHEER</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<!-- Page header options -->
<div class="row mb-3">
    <div class="col">
        <a class="btn btn-secondary" href="
               <?= $this->url('beheer/users', ['action' => 'add']); ?>">
            <i class="fas fa-plus-square"></i> New User
        </a>
    </div>
</div>
<div class="row">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>E-mail</th>
                <th>Full Name</th>
                <th>Date Created</th>
                <th>Status</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($users as $user): ?>
                <tr>
                    <td><?= $this->escapeHtml($user->getId()); ?></td>
                    <td>
                        <a href="<?= $this->url('beheer/users', ['action' => 'view', 'id' => $user->getId()]); ?>">
                            <?= $this->escapeHtml($user->getEmail()); ?>
                        </a>
                    </td>
                    <td><?= $this->escapeHtml($user->getFullName()); ?></a>
                    </td>
                    <td><?= (is_object($user->getDateCreated()) ? $user->getDateCreated()->format('d-m-Y') : ''); ?></td>
                    <td><?= $user->getStatusAsString(); ?></td>
                    <td class="text-center">
                        <a class="btn btn-sm btn-secondary" title="Edit user"
                           href="<?= $this->url('beheer/users', ['action' => 'edit', 'id' => $user->getId()]);
                           ?>">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-sm btn-secondary" title="Change password"
                           href="<?= $this->url('beheer/users', ['action' => 'change-password', 'id' => $user->getId()]);
                           ?>">
                            <i class="fas fa-key"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>