<?php
$this->headTitle('Set New Password');

$form->get('new_password')->setAttributes(array(
    'class' => 'form-control',
    'placeholder' => 'Type New Password'
));
$form->get('confirm_new_password')->setAttributes(array(
    'class' => 'form-control',
    'placeholder' => 'Confirm New Password'
));
$form->get('submit')->setAttributes(array(
    'class' => 'btn btn-primary'
));
$form->prepare();
?>
<div class="row">
    <hgroup style="background-image: url('../../img/headImages/road.jpg');" id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
        <h1 id="index">Set New Password</h1>
    </hgroup>
</div>
<div class="row">
    <div class="container">
        <?= $this->form()->openTag($form); ?>

        <p>Enter your new password in the form below</p>

        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>                              
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>   
        </div>    

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>