<?php
$this->layout('layout/beheer');
$this->headTitle('View User');

$this->mainMenu()->setActiveItemId('overviewusers');

$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Users' => $this->url('beheer/users'),
    'View User' => $this->url('beheer/users', ['action' => 'view', 'id' => $user->getId()])
]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>


<hgroup class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">View User <?= $this->escapeHtml($user->getEmail()) ?>Bla</h1>
</hgroup>
<div class="col-sm-12 col-md-12 col-lg-12">
    <p>
        <a class="btn btn-default" href="<?= $this->url('beheer/users', ['action' => 'edit', 'id' => $user->getId()]);
?>">
            <span class="glyphicon glyphicon-pencil" ></span> Edit
        </a>
        <a class="btn btn-default" href="<?= $this->url('beheer/users', ['action' => 'change-password', 'id' => $user->getId()]);
?>">
            <span class="glyphicon glyphicon-asterisk"></span> Change Password
        </a>    
    </p>
    <table class="table table-striped table-bordered">
        <tr>
            <th>ID:</th>
            <td><?= $this->escapeHtml($user->getId()) ?></th>
        </tr>
        <tr>
            <th>E-mail:</th>
            <td><?= $this->escapeHtml($user->getEmail()) ?></th>
        </tr>
        <tr>
            <th>Full Name:</th>
            <td><?= $this->escapeHtml($user->getFullName()) ?></th>
        </tr>
        <tr>
            <th>Date Created:</th>
            <td><?= (is_object($user->getDateCreated()) ? $user->getDateCreated()->format('d-m-Y') : ''); ?></th>
        </tr>
        <tr>
            <th>Status:</th>
            <td><?= $user->getStatusAsString() ?></th>
        </tr>
        <tr>
            <th>Roles:</th>
            <td><?= $this->escapeHtml($user->getRolesAsString()) ?></th>
        </tr>
    </table>
</div>