<!-- Header -->

<header class="header" id="top">
    <div class="pyro">
        <div class="before"></div>
        <div class="after"></div>
    </div>

    <div class="text-vertical-center">
        <h1 class="index-title">Verzeilberg</h1>
        <h3 class="index-sub-title">a (un)common name</h3>
        <br>
        <a href="#about" class="btn btn-dark btn-lg js-scroll-trigger"><i
                    class="fas fa-angle-double-down fa-3x"></i></a>
    </div>
</header>

<!-- About -->
<section id="about" class="about">
    <div class="container text-center">
        <h2><?php echo $this->translate('More?'); ?>&hellip;</h2>
        <p class="lead">
            This is my personal website. You can find some information about me. But the important thing is that this is
            a playground for me to work with ZF3, Bootstrap, CSS, jQuery, JavaScript.
        </p>
        <p class="lead">
            The design may be a bit of a dissapointment, but I am not a designer. So any suggestion may come in handy.
        </p>
        <p>
            <a href="<?php echo $this->url('about'); ?>" class="btn btn-dark btn-lg js-scroll-trigger"><i
                        class="fas fa-angle-double-right fa-3x"></i></a>
        </p>
    </div>
    <!-- /.container -->
</section>
<!-- Run stats -->
<?php
echo $this->partial('partial/run_stats.phtml', array(
    'totalRunActivities' => $totalRunActivities,
    'totalRunDistance' => $totalRunDistance,
    'totalRunTime' => $totalRunTime,
    'averageSpeed' => $averageSpeed,
    'averageElevation' => $averageElevation,
    'averageHeartbeat' => $averageHeartbeat,
    'activitiesOfThisMonth' => $activitiesOfThisMonth
));
?>

<!-- Tweets -->
<?php
echo $this->partial('partial/tweets.phtml', array('tweets' => $tweets));
?>
<!-- Events -->
<?php
if (is_object($upcommingEvent)) {
    echo $this->partial('partial/event.phtml', array('upcommingEvent' => $upcommingEvent));
}
?>
<!-- Blogs -->
<?php
echo $this->partial('partial/blogs.phtml', array('blogs' => $blogs));
?>
<!-- Contact form -->
<?php
echo $this->partial('partial/contact.phtml', array('form' => $form, 'post' => $post));
?>

