<?php
$this->headTitle('Running stats');
$this->mainMenu()->setActiveItemId('runningStats');
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Running stats' => $this->url('runningStats'),
]);
?>
<!-- Page Header -->
<header class="masthead" style="background-image: url('img/bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1 class="index-title">Running stats</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Breadcrumbs -->
<?= $this->pageBreadcrumbs()->render(); ?>
<!-- Main Content -->
<div class="container" id="runningStats">

    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="card btn-dark">
                <form id="selectYear" method="post">
                    <div class="row mt-2 mb-2">
                        <div class="col text-right">
                            <label class="col-form-label sr-only" for="year">Jaar</label>
                        </div>
                        <div class="col-4">
                            <select name="year" id="year" class="form-control form-control-sm">
                                <?php foreach($years AS $year) { ?>
                                    <option <?= ($currentYear == $year['jaar']? 'selected':'') ?> value="<?=$year['jaar']?>"><?= $year['jaar']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="col-4">
                            <select name="month" id="month" class="form-control form-control-sm">
                                <?php foreach($months AS $index => $month) { ?>
                                <option <?= ($currentMonth == $index? 'selected':'') ?> value="<?=$index?>"><?= $month; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="col text-left">
                            <label class="col-form-label sr-only" for="category">Maand</label>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col text-center">
            <canvas id="myChart" width="20%"></canvas>
        </div>
    </div>
</div>
<script>

    var ctx = document.getElementById('myChart').getContext('2d');
    var mixedChart = new Chart(ctx, {
        type: 'bar',
        data: {
            datasets: [{
                label: 'Afstand per activiteit in km',
                data: []
            }, {
                label: 'Totale afstand deze maand in km',
                data: [],
                backgroundColor: [
                    'rgba(255,0,0,0.0)'
                ],
                borderWidth: 5,
                borderColor: "#dc3545",
                // Changes this dataset to become a line
                type: 'line'
            }],
            labels: [
                <?php foreach($activitiesOfThisMonth AS $activity) { ?>
                "<?= $activity->getStartDate()->format('Y-m-d')?>",
                <?php } ?>
            ]
        },
        options: {
            title: {
                display: true,
                text: 'Afstand per activiteit ten opzichte van totale afstand deze maand',
                fontSize: 16,
                fontColor: 'black',
                fontFamily: 'Arial, Verdana'
            },
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true,
                        fontColor: "black"
                    },
                    gridLines: {
                        display: false,
                        color: "#000000",
                        fontColor: 'white',
                    },
                }],
                xAxes: [{
                    gridLines: {
                        display: false,
                        color: "#000000",
                        fontColor: 'black',
                    },
                    ticks: {
                        fontColor: "black"
                    },
                }]
            },
            legend: {
                labels: {
                    // This more specific font property overrides the global property
                    fontColor: 'black',
                    defaultFontFamily: 'Arial, Verdana'
                }
            },

        }
    });

    /*
     * When changing year or month select initialise getChartData
     */
    $('select#year, select#month').change(function() {
        getChartData();
    });

    /*
     * Get chart data based on year and month
     *
     * @return json
     */
    function getChartData() {

        var year = $('select#year').val();
        var month = $('select#month').val();

        $.ajax({
            type: 'POST',
            data: {
                year: year,
                month: month
            },
            url: "<?= $this->url('getChartData'); ?>",
            async: true,
            success: function (data) {
                if (data.success === true) {
                    mixedChart.data.labels = data.activitiesOfThisMonth.labels;
                    mixedChart.data.datasets[0].data = data.activitiesOfThisMonth.kmPerActivity;
                    mixedChart.data.datasets[1].data = data.activitiesOfThisMonth.kmActivityCumulatief;
                    mixedChart.update();

                } else {
                    alert(data.errorMessage);
                }
            }
        });
    }


    $(document).ready(function () {
        getChartData()
    });
</script>
